const rows = [
    {
      id: 1,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'N/A',
      start_date: '09/23/2016',
      type:'Youtube',
      information:"💎 YouTube Aged Accounts ⌛ 2006 - 2009 with Videos 🔥Full Data Change: Yes✔️",
      price:"10.00",
      seller:"VIP",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 2,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'Global',
      start_date: '09/23/2016',
      type:'Instagram',
      information:"💎INSTAGRAM ACCOUNT 2016 ⭐Followers: 1110+ ⚡️ Profile Photos: Male 🖼️ Have Posts: 9 Posts✔️ 💌Email Access: Yes✔️ 🔥Full Data Change: Yes✔️",
      price:"15.00",
      seller:"CheapDealer",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 3,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'Global',
      start_date: '09/23/2016',
      type:'Instagram',
      information:"💎INSTAGRAM ACCOUNT 2017 ⭐Followers: 1150+ ⚡️ Profile Photos: Male 🖼️ Have Posts: 18 Posts✔️ 💌Email Access: Yes✔️ 🔥Full Data Change: Yes✔️",
      price:"15.00",
      seller:"CheapDealer",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 4,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'N/A',
      start_date: '09/23/2016',
      type:'Youtube',
      information:"💎 YouTube Aged Accounts ⌛ 2006 - 2009 with Videos 🔥Full Data Change: Yes✔️",
      price:"10.00",
      seller:"VIP",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    
  ]
  export default rows