export const rows = [

    {
      id: 1,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'USA',
      start_date: '09/23/2016',
      type:'IPVanish',
      information:"Active VPN Account , PLAN = PRO , Expiry = 2024-04-10",
      price:"10.00",
      seller:"Magnus0VIP",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 2,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'United States',
      start_date: '09/23/2016',
      type:'Hotspotshield',
      information:"Plan:Premium - IsExpired:False - isFamilyMember:False",
      price:"15.00",
      seller:"SBKiing",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 3,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'US',
      start_date: '09/23/2016',
      type:'IPVanish',
      information:"ACTIVE ACCOUNT , Expiry = 2024-01-31",
      price:"15.00",
      seller:"Alpha-1",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 4,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'United States',
      start_date: '09/23/2016',
      type:'Hotspotshield',
      information:"Plan:Premium - IsExpired:False - isFamilyMember:False",
      price:"10.00",
      seller:"SBKiing",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    
  ]
  