export const rows = [
    {
      id: 1,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'United States	',
      start_date: '09/23/2016',
      type:'Crunchyroll',
      information:"Type:premium",
      price:"6.00",
      seller:"SBKiing",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 2,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'US',
      start_date: '09/23/2016',
      type:'AcornTV',
      information:"AcornTV Premium - NextBilling: 11/12/2022, PostalCode: 87111",
      price:"5.00",
      seller:"VIP",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 3,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'USA',
      start_date: '09/23/2016',
      type:'Netflix',
      information:"Plan Type = Estándar , Video Quality = HD , Payment Method = CC",
      price:"12.00",
      seller:"CheapDealer",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 4,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'N/A',
      start_date: '09/23/2016',
      type:'CrunChyroll',
      information:"Type = premium , Category = anime/drama/manga",
      price:"10.00",
      seller:"VIP",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    
  ]
  