export const rows = [
    {
      id: 1,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'Global',
      start_date: '09/23/2016',
      type:'Malwarebytes',
      information:"🔥Malwarebytes Anti-Malware Premium ✅(PC) Windows&Mac / 1 Device Guaranteed🔰 / Expiry date: LIFETIME / Only License KEY🔑",
      price:"14.99",
      seller:"bestseller777",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 2,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'N/A',
      start_date: '09/23/2016',
      type:'Malwarebytes',
      information:"MAlwareByte Premium Antivirus",
      price:"5.00",
      seller:"VIP",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 3,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'Global',
      start_date: '09/23/2016',
      type:'Malwarebytes',
      information:"🔥Malwarebytes Anti-Malware Premium ✅(PC) Windows&Mac / 1 Device Guaranteed🔰 / Expiry date: LIFETIME / Only License KEY🔑",
      price:"14.99",
      seller:"bestseller777",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    {
      id: 4,
      avatar: '8.png',
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'kocrevy0@thetimes.co.uk',
      country: 'N/A',
      start_date: '09/23/2016',
      type:'Malwarebytes',
      information:"🔥Malwarebytes Anti-Malware Premium ✅(PC) Windows&Mac / 1 Device Guaranteed🔰 / Expiry date: LIFETIME / Only License KEY🔑",
      price:"14.99",
      seller:"bestseller777",
      salary: 23896.35,
      age: '61',
      experience: '1 Year',
      status: 2
    },
    
  ]
  